### ISSUE TITLE
Disable tagging house when applying points to a user

### ISSUE THREAD

**Issue by LadyBrittany** [Audentio/housecup-bot-issues#1]
part suggestion but may be a bug as well. 
So when you add the bot and have houses (we did the four original) and you add points to a person lets say someone in Ravenclaw, Ravenclaw house does not get those points. BUT if you add points to the house it gives points to every person in that house. So it should be flipped. if a person earns points so does the house as a whole, and if a person loses points so does the house as a whole. if the house as a whole earns or loses points they don't go to any one person

**Comment by JakeBooher** [comment]
I've just double checked the functionality on this. The way it is intended to work (and is currently working) is:

If points are awarded to or taken from an **individual user** the points are also awarded to or taken from the house, which I think we're both agreeing is the desired behavior (Though it sounds like this isn't happening for you? Could you get me a screenshot of what is happening for you specifically?)

![Screen Shot 2019-11-11 at 10 31 53 AM](https://user-images.githubusercontent.com/179180/68603758-902cf300-046e-11ea-9247-c365f73a46be.png)

If points are awarded to or taken from a **house**, however, the points do currently get awarded to or taken from each user in the house as well. I _think_ this is what makes the most sense, but am definitely open to feedback. What is the reason it shouldn't be applied to individual users? I don't particularly have a reason for the way I did it specifically, so definitely open to a change :)

**Comment by LadyBrittany** [comment]
I can get you a screenshot for sure! 
![image](https://user-images.githubusercontent.com/34496296/68604052-970c3380-0477-11ea-97af-5624d9b90387.png)
So as you can see with our leader board we have a bunch of people with points but none of the houses have them even though they should. 

I kicked the bot and readded it (to same server) so that i dont have two roles (while i was testing) and now i cant register the houses again OR see the leaderboard

**Comment by LadyBrittany** [comment]
![image](https://user-images.githubusercontent.com/34496296/68605483-7abdc600-047a-11ea-9a35-72e436e2c0ed.png)
mkay so only tried to added slytherin again but apparently even if you kick the bot and readd it, it keeps everything from before which is totally fine. I would suggest a command that says this house is already registered with a reminder of how to check the list of registered houses.

**Comment by JakeBooher** [comment]
Thanks for letting us know on that, I've split it out into a separate issue to keep things a bit easier to follow. Could you reply to that issue with the details I've requested there? :)

As for this original issue - are you certain those points weren't added before the houses were registered? The points won't be retroactively added to a house if you register the house later, or add a user into the associated user group after the points have been given. If you're certain this is the case, could you [Create a ticket](https://housecup.gg/support) with the name of your Slack workspace, as well as the short name (The one that appears in the URL of your workspace?)

**Comment by LadyBrittany** [comment]
I can but we only use it on discord, so I can give you that information?

**Comment by LadyBrittany** [comment]
I'll just copy pasta from the other one to be safe >.>
Discord server: discord.gg/AYjxSzw
Lady Brittany #4877

When you join let me know it is you and I will give you temp perms to see our bot commands channel! that way you can mess with it as well!

**Comment by JakeBooher** [comment]
I've just joined:
JakeB #2775

**Comment by LadyBrittany** [comment]
All set! sorry we had an event going on, on our discord and was handling that!

**Comment by JakeBooher** [comment]
@LadyBrittany I'm getting some errors logged from Discord's API saying the bot doesn't have permission to create that specific leaderboard message in that channel. Do you have any sort of limit on how many tags can be made in a single message, or a limit on who can tag any of the roles that are registered as houses? Could you try adjusting permissions for the HouseCup bot user to make sure it can bypass any of these limitations?

**Comment by LadyBrittany** [comment]
We can, the issue we ran into that is that every time we award someone house points it pings everyone with that house role. I'll use James as an example:
@housecup 5 points to @james for being cool
The house cup then responds with:
5 points awarded to @james and @gryffindor
And then shows the totals for each.
The issue with that is anytime we wanted to give a single person points it would ping 100+ people since they share a house role with him. We found turning of allowing to ping the house meant the bot couldn't as well and wouldn't count them towards the house total but we would rather do math than ping 100+ people a bunch throughout the day if that makes sense. For bigger servers that have 500+ people getting pinged 10-20 times for something about someone else will drive people away from the server when this is to help encourage people to engage within the community

**Comment by JakeBooher** [comment]
Hm yeah, that makes sense. I think I can probably disable actually tagging the group. The bot was originally built for Slack, which is more typically used for a company's employees and I think it made sense there, but probably less so on Discord. I'll see about removing that, or making it an option :)
