### ISSUE TITLE
I have some Bugs with the bot

### ISSUE THREAD

**Issue by adriengauthier64** [Audentio/housecup-bot-issues#10]
![Uploading BF0AF278-AEA4-4872-80A1-DA13ACE31F2B.jpeg…]()
Good evening, i have some problems with Housecup. The Leaderboard command don’t work and i cannot register Houses. The list of the members is not complete some people are missing in the list. Thanks for your help. 
Adrien

**Comment by themattman18** [comment]
Do you have any more details on this bug? Are you using Slack or Discord?

**Comment by adriengauthier64** [comment]
Hello. I’m using Discord. I don’t have any error when i use some commands like Leaderboard or when i want to give points it dosn’t work all Times.  Just nothing appens.

**Comment by themattman18** [comment]
Have you tired referencing the bot with @housecup#3289
This is a work around for a known bug on Discord where @housecup doesn't work all the time.  You'll have to manually type this as copying and pasting doesn't seem to work.
See issue #5

**Comment by adriengauthier64** [comment]
In fact some commands work properly. Help work fine  List houses work fine, permit work fine, giving points work too but only with members not for the houses.. Leaderboard and register houses are not working. When i use them anything is happening thanks for your help

**Comment by themattman18** [comment]
How did you try to register your houses? Did you create the server roles and make them mentionable?

**Comment by adriengauthier64** [comment]
Yes everything was okay past week. I have my houses but i cannot add new ones. And some members are missing. I use the commend mentioned in help @housecup register house @housename
