### ISSUE TITLE
Unregister houses

### ISSUE THREAD

**Issue by Forfeitdaisy552** [Audentio/housecup-bot-issues#13]
Hey, I recently got house cup bot on my server, had some troubles registering houses, realized it was because I needed to make the roles mention able. But while trying to figure it out, I added random roles, to see if it would work, and they did. I'm just trying to figure out how to take those roles out of the house cup. There is no command for it, and I even tried kicking the bot and re inviting it, any help would be great, thanks.

**Comment by StephenAtech** [comment]
I would also love to know how to do this.

**Comment by JakeBooher** [comment]
This is now possible using the `delete house` command
