### ISSUE TITLE
Removing user from role won't remove from house

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/housecup-bot-issues#2]
![image](https://user-images.githubusercontent.com/34496296/68605483-7abdc600-047a-11ea-9a35-72e436e2c0ed.png)
mkay so only tried to added slytherin again but apparently even if you kick the bot and readd it, it keeps everything from before which is totally fine. I would suggest a command that says this house is already registered with a reminder of how to check the list of registered houses.

_Originally posted by @LadyBrittany _

Split from #1

**Comment by JakeBooher** [comment]
I'll have a look into why this is occurring, but in the mean time, could you [Create a ticket](https://housecup.gg/support) with the name of your Slack workspace, as well as the short name (The one that appears in the URL of your workspace?) and I'll manually reapply the permissions?

**Comment by LadyBrittany** [comment]
I can but we only use it on discord, so I can give you that information?
Discord server: discord.gg/AYjxSzw
Lady Brittany #4877

When you join let me know it is you and I will give you temp perms to see our bot commands channel! that way you can mess with it as well!

**Comment by JakeBooher** [comment]
I've just joined:
JakeB #2775

**Comment by JakeBooher** [comment]
I've found your Discord account twice in the database on two different Discord servers, and you seem to have full permissions on both. What did you see to indicate that you didn't have permissions?

**Comment by LadyBrittany** [comment]
There is only one of me, I'm listed twice because when I was testing stuff (to see points awarded) I gave myself the Gryffindor role so now it lists me there even though I'm not longer in the house. 
When you kick the bot instead of removing everything it comes back as if it never left. House points are all the same and houses still exsist instead of having to re add them. I had hoped removing it would let it realize I am only in one house. There are two different servers and I do have permission on both of them for the bot (as it was my idea to add it) but only one of me. On the wizarding news server (that you have permissions in) you'll see me listed twice when I shouldn't be.

**Comment by JakeBooher** [comment]
So it keeping the points and everything as is if you kick the bot was intentional as  originally we cleared this out but a couple times the bot was removed by mistake and people lost all of their data. We've got a feature coming soon that will let you login to a web page to clear all the data for the server. However, if you remove yourself from the Gryffindor role it definitely should remove you from it on our end as well, so I think there may be an issue there. I'll rename the issue to be more clear and see about getting that sorted out :)

**Comment by JakeBooher** [comment]
@LadyBrittany This actually appears to be behaving how it was intended, it won't rebuild the list of users in a house until someone attempts to add points to the house, and it's only done at most every 15 minutes this is done as the process to update this is quite heavy and it's not something that should be changing regularly. Once someone adds points to your Gryffindor house (either directly or through a user) it will rebuild :)

**Comment by LadyBrittany** [comment]
I tried to add points to just the house, and to someone with gryffindor to fix it >.> ill wait 15 minutes and try again 

![image](https://user-images.githubusercontent.com/34496296/68876033-cf0eb300-06d1-11ea-8066-ad520c580ebd.png)
