### ISSUE TITLE
Unable to register houses on Slack

### ISSUE THREAD

**Issue by yousefhalabi** [Audentio/housecup-bot-issues#25]
## Problem
On Slack, whenever i try to register a house i get the following answer:

> House Cup (App)  1:03 PM
You must specify at least one group to register as a house. This group must also be mentionable by all users if you are using Discord.

PS: this message makes me wonder if HouseCup is designed only for discord.

## Debug:
> House Cup (App)  1:04 PM
Server ID: T015Q3Q6BQ8
Server Type: slack
User ID: U0150EN6S91
Channel ID: C0156DTADKN
Last Data Sync: 2020-06-08T00:00:00+00:00

## Context:
new slack workspace with 1 member
installed @housecup and added to public channel
from that public channel i have tried the command "@HouseCup register house" with many variances including:
- #a-public-channel
- a-public-channel
- #public-channel-id 
- channel-id
- public-channel-name
- #a-private-channel 
- just-a-plain-name
- @username
- username
and other ways but you get the idea.

**Comment by JakeBooher** [comment]
For slack you'll need to create a usergroup and register it by tagging that group. Details on how to create one are here: https://slack.com/help/articles/212906697-Create-a-user-group
