### ISSUE TITLE
HouseCup not restarting (and other issues)

### ISSUE THREAD

**Issue by eternaldoritopaladin** [Audentio/housecup-bot-issues#4]
I'm in a Harry Potter RP server. The bot hasn't been registering houses properly and it's been having issues with giving/taking points, so we tried to restart it, and it won't restart either.

**Comment by JakeBooher** [comment]
Could you provide details on what you've tried that hasn't worked, any error messages you've received, etc?

Are you running it on Slack or Discord, and what exactly do you mean when you say you tried to restart it?

**Comment by eternaldoritopaladin** [comment]
This is the issue I’m having. It won’t restart the cup, and I did try
typing out the full name.
