### ISSUE TITLE
HouseCup response issues

### ISSUE THREAD

**Issue by courts2041** [Audentio/housecup-bot-issues#5]
HouseCup doesn't respond unless you type in the full name.

Tried typing @HouseCup and clicking on the bot name - No response
Tried typing @HouseCup and hitting enter to populate - No response
Tried typing @HouseCup#3289 and it will respond.

![image](https://user-images.githubusercontent.com/58781380/70634318-9cd07280-1bf7-11ea-8f46-00c28ef6f244.png)

**Comment by courts2041** [comment]
Also on discord right now. TOld my users to use the workaround for now

**Comment by eternaldoritopaladin** [comment]
This is the issue I’m having. It won’t restart the cup, and I did try
typing out the full name.

**Comment by courts2041** [comment]
It's working for me now as of this morning!
