### ISSUE TITLE
HouseCup not registering icons/colors and switching channels

### ISSUE THREAD

**Issue by witchybrew** [Audentio/housecup-bot-issues#7]
![37404E56-C342-40DE-9A2D-B8CF26E99E8F](https://user-images.githubusercontent.com/59669739/72020311-25f7bb00-3231-11ea-88a4-f0521cc2486e.png)
![CEF59DF5-C0DB-4903-B26D-7E427A0A0B06](https://user-images.githubusercontent.com/59669739/72020312-25f7bb00-3231-11ea-9f36-cbedaf9b47e3.png)

Hi all! Currently my house cup is taking points away fine but will only respond to prompts in a single channel! It also won’t register icon or color customizations.

**Comment by JakeBooher** [comment]
The color won't show up in the text, it's only used on the image generated that has the outcome (I believe you just tag @HouseCup without any sort of additional parameters), seems to be behaving as expected
