### ISSUE TITLE
Bot doesn't respond on PC

### ISSUE THREAD

**Issue by Wendy-Wendy** [Audentio/housecup-bot-issues#8]
When I send commands via my pc, the bot does not answer. We have this problem already some time and we don't know how to fix it.
I'm not the only one with this problem, as it happens to all people on my server. Only if you send the command via phone, it start working.

![image](https://user-images.githubusercontent.com/62255081/76777155-0f795d00-67a8-11ea-8c7c-2c9aa6118123.png)

**Comment by JakeBooher** [comment]
This is because of #6
