### ISSUE TITLE
Registering houses

### ISSUE THREAD

**Issue by Rez4nn** [Audentio/housecup-bot-issues#9]
I am sure I have done this all correctly, but when I try and register a group, this happens:
![Screenshot_20200412-203413_Discord](https://user-images.githubusercontent.com/63560091/79078103-01165680-7cfe-11ea-8e6b-c8c26e607342.jpg)

**Comment by themattman18** [comment]
I have the same issue.  Did you just create server roles to register as a house?

**Comment by themattman18** [comment]
I figured it out.  You have to modify your server role so anyone can mention it.
I created a server role called Gryffindor and allowed anyone on the server to mention it
![image](https://user-images.githubusercontent.com/2312966/79988902-d3a37880-8474-11ea-93f3-521a5b1c2bf4.png)
